// Auth
export const USERNAME_SUFFIX = '@sinar-gold.com'
export const MIN_PASSWORD_LENGTH = 7
export const CUSTOM_CLAIMS_ROLE = 'role'

// Firestore
export const COLLECTION_USERS = 'users'
export const COLLECTION_CRAFTSMAN_ORDER = 'craftsmanOrder'

// Database
export const NODE_MASTER_DATA = 'masterData'
export const NODE_BANK = 'bank'
export const NODE_GROUP = 'group'
export const NODE_KIND = 'kind'
export const NODE_WAREHOUSE = 'warehouse'
export const NODE_ITEM_TYPE = 'itemType'
export const NODE_GROUP_TYPE = 'groupType'
export const NODE_CHAMFER = 'chamfer'
export const NODE_TAG = 'tag'
export const NODE_POINT = 'point'
export const NODE_SALESMAN = 'salesman'
export const NODE_CRAFTSMAN = 'craftsman'
export const NODE_GIFT = 'gift'
export const NODE_MARKETPLACE = 'marketplace'
export const NODE_STOREFRONT = 'storefront'
export const NODE_TRANSACTION_CODE = 'transactionCode'
export const NODE_GOLD_PRICE = 'goldPrice'
export const NODE_ITEM_CONDITION = 'itemCondition'
export const NODE_COST = 'cost'
export const NODE_PURCHASE_CONDITION = 'purchaseCondition'
export const NODE_STORE = 'store'
export const NODE_CASH_CATEGORY = 'cashCategory'
export const NODE_NOTE_DESCRIPTION = 'noteDescription'
export const NODE_BANK_ACCOUNT_NUMBER = 'bankAccountNumber'
export const NODE_DIAMOND = 'diamond'
export const NODE_SUPPLIER = 'supplier'
export const NODE_SHAPE = 'shape'
export const NODE_COLOR = 'color'
export const NODE_CLARITY = 'clarity'
export const NODE_FLUORESCENCE = 'fluorescence'
export const NODE_SYMMETRY = 'symmetry'
export const NODE_POLISH = 'polish'
export const NODE_CUT_GRADE = 'cutGrade'
export const NODE_STONE_TYPE = 'stoneType'

// Cloud Functions
export const CLOUD_FUNCTIONS_DEFAULT_REGION = 'asia-southeast2'
